// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: solution.proto

package solution

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// SolutionServerService defines service.
type SolutionServerService interface {
	// QueryRuntimeInfo QueryRuntimeInfo 查询信息
	QueryRuntimeInfo(ctx context.Context, req *QueryRuntimeInfoReq) (*QueryRuntimeInfoRsp, error)
	// QuerySourceCode QuerySourceCode 查询源代码
	QuerySourceCode(ctx context.Context, req *QuerySourceCodeReq) (*QuerySourceCodeRsp, error)
	// AddSolution AddSolution 添加提交数据
	AddSolution(ctx context.Context, req *AddSolutionReq) (*AddSolutionRsp, error)
	// QuerySolution QuerySolution 查询提交数据
	QuerySolution(ctx context.Context, req *QuerySolutionReq) (*QuerySolutionRsp, error)
}

func SolutionServerService_QueryRuntimeInfo_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &QueryRuntimeInfoReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(SolutionServerService).QueryRuntimeInfo(ctx, reqbody.(*QueryRuntimeInfoReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func SolutionServerService_QuerySourceCode_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &QuerySourceCodeReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(SolutionServerService).QuerySourceCode(ctx, reqbody.(*QuerySourceCodeReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func SolutionServerService_AddSolution_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &AddSolutionReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(SolutionServerService).AddSolution(ctx, reqbody.(*AddSolutionReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func SolutionServerService_QuerySolution_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &QuerySolutionReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(SolutionServerService).QuerySolution(ctx, reqbody.(*QuerySolutionReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// SolutionServerServer_ServiceDesc descriptor for server.RegisterService.
var SolutionServerServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "oj.java.solution.SolutionServer",
	HandlerType: ((*SolutionServerService)(nil)),
	Methods: []server.Method{
		{
			Name: "/oj.java.solution.SolutionServer/QueryRuntimeInfo",
			Func: SolutionServerService_QueryRuntimeInfo_Handler,
		},
		{
			Name: "/oj.java.solution.SolutionServer/QuerySourceCode",
			Func: SolutionServerService_QuerySourceCode_Handler,
		},
		{
			Name: "/oj.java.solution.SolutionServer/AddSolution",
			Func: SolutionServerService_AddSolution_Handler,
		},
		{
			Name: "/oj.java.solution.SolutionServer/QuerySolution",
			Func: SolutionServerService_QuerySolution_Handler,
		},
	},
}

// RegisterSolutionServerService registers service.
func RegisterSolutionServerService(s server.Service, svr SolutionServerService) {
	if err := s.Register(&SolutionServerServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("SolutionServer register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedSolutionServer struct{}

// QueryRuntimeInfo QueryRuntimeInfo 查询信息
func (s *UnimplementedSolutionServer) QueryRuntimeInfo(ctx context.Context, req *QueryRuntimeInfoReq) (*QueryRuntimeInfoRsp, error) {
	return nil, errors.New("rpc QueryRuntimeInfo of service SolutionServer is not implemented")
}

// QuerySourceCode QuerySourceCode 查询源代码
func (s *UnimplementedSolutionServer) QuerySourceCode(ctx context.Context, req *QuerySourceCodeReq) (*QuerySourceCodeRsp, error) {
	return nil, errors.New("rpc QuerySourceCode of service SolutionServer is not implemented")
}

// AddSolution AddSolution 添加提交数据
func (s *UnimplementedSolutionServer) AddSolution(ctx context.Context, req *AddSolutionReq) (*AddSolutionRsp, error) {
	return nil, errors.New("rpc AddSolution of service SolutionServer is not implemented")
}

// QuerySolution QuerySolution 查询提交数据
func (s *UnimplementedSolutionServer) QuerySolution(ctx context.Context, req *QuerySolutionReq) (*QuerySolutionRsp, error) {
	return nil, errors.New("rpc QuerySolution of service SolutionServer is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// SolutionServerClientProxy defines service client proxy
type SolutionServerClientProxy interface {
	// QueryRuntimeInfo QueryRuntimeInfo 查询信息
	QueryRuntimeInfo(ctx context.Context, req *QueryRuntimeInfoReq, opts ...client.Option) (rsp *QueryRuntimeInfoRsp, err error)
	// QuerySourceCode QuerySourceCode 查询源代码
	QuerySourceCode(ctx context.Context, req *QuerySourceCodeReq, opts ...client.Option) (rsp *QuerySourceCodeRsp, err error)
	// AddSolution AddSolution 添加提交数据
	AddSolution(ctx context.Context, req *AddSolutionReq, opts ...client.Option) (rsp *AddSolutionRsp, err error)
	// QuerySolution QuerySolution 查询提交数据
	QuerySolution(ctx context.Context, req *QuerySolutionReq, opts ...client.Option) (rsp *QuerySolutionRsp, err error)
}

type SolutionServerClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewSolutionServerClientProxy = func(opts ...client.Option) SolutionServerClientProxy {
	return &SolutionServerClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *SolutionServerClientProxyImpl) QueryRuntimeInfo(ctx context.Context, req *QueryRuntimeInfoReq, opts ...client.Option) (*QueryRuntimeInfoRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.java.solution.SolutionServer/QueryRuntimeInfo")
	msg.WithCalleeServiceName(SolutionServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("SolutionServer")
	msg.WithCalleeMethod("QueryRuntimeInfo")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &QueryRuntimeInfoRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *SolutionServerClientProxyImpl) QuerySourceCode(ctx context.Context, req *QuerySourceCodeReq, opts ...client.Option) (*QuerySourceCodeRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.java.solution.SolutionServer/QuerySourceCode")
	msg.WithCalleeServiceName(SolutionServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("SolutionServer")
	msg.WithCalleeMethod("QuerySourceCode")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &QuerySourceCodeRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *SolutionServerClientProxyImpl) AddSolution(ctx context.Context, req *AddSolutionReq, opts ...client.Option) (*AddSolutionRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.java.solution.SolutionServer/AddSolution")
	msg.WithCalleeServiceName(SolutionServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("SolutionServer")
	msg.WithCalleeMethod("AddSolution")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &AddSolutionRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *SolutionServerClientProxyImpl) QuerySolution(ctx context.Context, req *QuerySolutionReq, opts ...client.Option) (*QuerySolutionRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.java.solution.SolutionServer/QuerySolution")
	msg.WithCalleeServiceName(SolutionServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("SolutionServer")
	msg.WithCalleeMethod("QuerySolution")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &QuerySolutionRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
