// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: test.proto

package pb

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// HelloserverService defines service.
type HelloserverService interface {
	SayHello(ctx context.Context, req *HelloRequest) (*HelloReply, error)
}

func HelloserverService_SayHello_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &HelloRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(HelloserverService).SayHello(ctx, reqbody.(*HelloRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// HelloserverServer_ServiceDesc descriptor for server.RegisterService.
var HelloserverServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "baomin.Helloserver",
	HandlerType: ((*HelloserverService)(nil)),
	Methods: []server.Method{
		{
			Name: "/baomin.Helloserver/SayHello",
			Func: HelloserverService_SayHello_Handler,
		},
	},
}

// RegisterHelloserverService registers service.
func RegisterHelloserverService(s server.Service, svr HelloserverService) {
	if err := s.Register(&HelloserverServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("Helloserver register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedHelloserver struct{}

func (s *UnimplementedHelloserver) SayHello(ctx context.Context, req *HelloRequest) (*HelloReply, error) {
	return nil, errors.New("rpc SayHello of service Helloserver is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// HelloserverClientProxy defines service client proxy
type HelloserverClientProxy interface {
	SayHello(ctx context.Context, req *HelloRequest, opts ...client.Option) (rsp *HelloReply, err error)
}

type HelloserverClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewHelloserverClientProxy = func(opts ...client.Option) HelloserverClientProxy {
	return &HelloserverClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *HelloserverClientProxyImpl) SayHello(ctx context.Context, req *HelloRequest, opts ...client.Option) (*HelloReply, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/baomin.Helloserver/SayHello")
	msg.WithCalleeServiceName(HelloserverServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Helloserver")
	msg.WithCalleeMethod("SayHello")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &HelloReply{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
