// Code generated by MockGen. DO NOT EDIT.
// Source: stub/github.com/csuJudge/judgeProto/code/code.trpc.go
//
// Generated by this command:
//
//	mockgen -destination=stub/github.com/csuJudge/judgeProto/code/code_mock.go -package=code -self_package=github.com/csuJudge/judgeProto/code --source=stub/github.com/csuJudge/judgeProto/code/code.trpc.go
//

// Package code is a generated GoMock package.
package code

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	client "trpc.group/trpc-go/trpc-go/client"
)

// MockCodeServerService is a mock of CodeServerService interface.
type MockCodeServerService struct {
	ctrl     *gomock.Controller
	recorder *MockCodeServerServiceMockRecorder
}

// MockCodeServerServiceMockRecorder is the mock recorder for MockCodeServerService.
type MockCodeServerServiceMockRecorder struct {
	mock *MockCodeServerService
}

// NewMockCodeServerService creates a new mock instance.
func NewMockCodeServerService(ctrl *gomock.Controller) *MockCodeServerService {
	mock := &MockCodeServerService{ctrl: ctrl}
	mock.recorder = &MockCodeServerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCodeServerService) EXPECT() *MockCodeServerServiceMockRecorder {
	return m.recorder
}

// ISGOMOCK indicates that this struct is a gomock mock.
func (m *MockCodeServerService) ISGOMOCK() struct{} {
	return struct{}{}
}

// AddCode mocks base method.
func (m *MockCodeServerService) AddCode(ctx context.Context, req *AddCodeReq) (*CommonRsp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCode", ctx, req)
	ret0, _ := ret[0].(*CommonRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddCode indicates an expected call of AddCode.
func (mr *MockCodeServerServiceMockRecorder) AddCode(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCode", reflect.TypeOf((*MockCodeServerService)(nil).AddCode), ctx, req)
}

// MockCodeServerClientProxy is a mock of CodeServerClientProxy interface.
type MockCodeServerClientProxy struct {
	ctrl     *gomock.Controller
	recorder *MockCodeServerClientProxyMockRecorder
}

// MockCodeServerClientProxyMockRecorder is the mock recorder for MockCodeServerClientProxy.
type MockCodeServerClientProxyMockRecorder struct {
	mock *MockCodeServerClientProxy
}

// NewMockCodeServerClientProxy creates a new mock instance.
func NewMockCodeServerClientProxy(ctrl *gomock.Controller) *MockCodeServerClientProxy {
	mock := &MockCodeServerClientProxy{ctrl: ctrl}
	mock.recorder = &MockCodeServerClientProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCodeServerClientProxy) EXPECT() *MockCodeServerClientProxyMockRecorder {
	return m.recorder
}

// ISGOMOCK indicates that this struct is a gomock mock.
func (m *MockCodeServerClientProxy) ISGOMOCK() struct{} {
	return struct{}{}
}

// AddCode mocks base method.
func (m *MockCodeServerClientProxy) AddCode(ctx context.Context, req *AddCodeReq, opts ...client.Option) (*CommonRsp, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddCode", varargs...)
	ret0, _ := ret[0].(*CommonRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddCode indicates an expected call of AddCode.
func (mr *MockCodeServerClientProxyMockRecorder) AddCode(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCode", reflect.TypeOf((*MockCodeServerClientProxy)(nil).AddCode), varargs...)
}
