// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: code.proto

package code

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddCodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProblemID     int32                  `protobuf:"varint,1,opt,name=problemID,proto3" json:"problemID,omitempty"` // 问题编号
	Language      int32                  `protobuf:"varint,2,opt,name=language,proto3" json:"language,omitempty"`   // 语言类型
	UserID        int32                  `protobuf:"varint,3,opt,name=userID,proto3" json:"userID,omitempty"`       // 用户编号
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`            // 代码
	CodeName      string                 `protobuf:"bytes,5,opt,name=codeName,proto3" json:"codeName,omitempty"`    // 代码名称
	SaveType      int32                  `protobuf:"varint,6,opt,name=saveType,proto3" json:"saveType,omitempty"`   // 保存类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCodeReq) Reset() {
	*x = AddCodeReq{}
	mi := &file_code_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCodeReq) ProtoMessage() {}

func (x *AddCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_code_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCodeReq.ProtoReflect.Descriptor instead.
func (*AddCodeReq) Descriptor() ([]byte, []int) {
	return file_code_proto_rawDescGZIP(), []int{0}
}

func (x *AddCodeReq) GetProblemID() int32 {
	if x != nil {
		return x.ProblemID
	}
	return 0
}

func (x *AddCodeReq) GetLanguage() int32 {
	if x != nil {
		return x.Language
	}
	return 0
}

func (x *AddCodeReq) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *AddCodeReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AddCodeReq) GetCodeName() string {
	if x != nil {
		return x.CodeName
	}
	return ""
}

func (x *AddCodeReq) GetSaveType() int32 {
	if x != nil {
		return x.SaveType
	}
	return 0
}

type CommonRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // 返回信息
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`      // 返回码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonRsp) Reset() {
	*x = CommonRsp{}
	mi := &file_code_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonRsp) ProtoMessage() {}

func (x *CommonRsp) ProtoReflect() protoreflect.Message {
	mi := &file_code_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonRsp.ProtoReflect.Descriptor instead.
func (*CommonRsp) Descriptor() ([]byte, []int) {
	return file_code_proto_rawDescGZIP(), []int{1}
}

func (x *CommonRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommonRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_code_proto protoreflect.FileDescriptor

const file_code_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"code.proto\x12\aoj.code\"\xaa\x01\n" +
	"\n" +
	"AddCodeReq\x12\x1c\n" +
	"\tproblemID\x18\x01 \x01(\x05R\tproblemID\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\x05R\blanguage\x12\x16\n" +
	"\x06userID\x18\x03 \x01(\x05R\x06userID\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12\x1a\n" +
	"\bcodeName\x18\x05 \x01(\tR\bcodeName\x12\x1a\n" +
	"\bsaveType\x18\x06 \x01(\x05R\bsaveType\"9\n" +
	"\tCommonRsp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code2B\n" +
	"\n" +
	"CodeServer\x124\n" +
	"\aAddCode\x12\x13.oj.code.AddCodeReq\x1a\x12.oj.code.CommonRsp\"\x00B%Z#github.com/csuJudge/judgeProto/codeb\x06proto3"

var (
	file_code_proto_rawDescOnce sync.Once
	file_code_proto_rawDescData []byte
)

func file_code_proto_rawDescGZIP() []byte {
	file_code_proto_rawDescOnce.Do(func() {
		file_code_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_code_proto_rawDesc), len(file_code_proto_rawDesc)))
	})
	return file_code_proto_rawDescData
}

var file_code_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_code_proto_goTypes = []any{
	(*AddCodeReq)(nil), // 0: oj.code.AddCodeReq
	(*CommonRsp)(nil),  // 1: oj.code.CommonRsp
}
var file_code_proto_depIdxs = []int32{
	0, // 0: oj.code.CodeServer.AddCode:input_type -> oj.code.AddCodeReq
	1, // 1: oj.code.CodeServer.AddCode:output_type -> oj.code.CommonRsp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_code_proto_init() }
func file_code_proto_init() {
	if File_code_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_code_proto_rawDesc), len(file_code_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_code_proto_goTypes,
		DependencyIndexes: file_code_proto_depIdxs,
		MessageInfos:      file_code_proto_msgTypes,
	}.Build()
	File_code_proto = out.File
	file_code_proto_goTypes = nil
	file_code_proto_depIdxs = nil
}
