// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: contest.proto

package contest

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContestFinishStatus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FinishCount      int32                  `protobuf:"varint,1,opt,name=finishCount,proto3" json:"finishCount,omitempty"`           // 完成数
	Participants     int32                  `protobuf:"varint,2,opt,name=participants,proto3" json:"participants,omitempty"`         // 参与人数
	NeedParticipants int32                  `protobuf:"varint,3,opt,name=needParticipants,proto3" json:"needParticipants,omitempty"` // 应参与人数
	LowestProblem    []*ContestProblem      `protobuf:"bytes,4,rep,name=lowestProblem,proto3" json:"lowestProblem,omitempty"`        // 通过率最低的三个题
	Name             string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`                          // 作业名称
	EndTime          string                 `protobuf:"bytes,6,opt,name=endTime,proto3" json:"endTime,omitempty"`                    // 结束时间
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ContestFinishStatus) Reset() {
	*x = ContestFinishStatus{}
	mi := &file_contest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContestFinishStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContestFinishStatus) ProtoMessage() {}

func (x *ContestFinishStatus) ProtoReflect() protoreflect.Message {
	mi := &file_contest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContestFinishStatus.ProtoReflect.Descriptor instead.
func (*ContestFinishStatus) Descriptor() ([]byte, []int) {
	return file_contest_proto_rawDescGZIP(), []int{0}
}

func (x *ContestFinishStatus) GetFinishCount() int32 {
	if x != nil {
		return x.FinishCount
	}
	return 0
}

func (x *ContestFinishStatus) GetParticipants() int32 {
	if x != nil {
		return x.Participants
	}
	return 0
}

func (x *ContestFinishStatus) GetNeedParticipants() int32 {
	if x != nil {
		return x.NeedParticipants
	}
	return 0
}

func (x *ContestFinishStatus) GetLowestProblem() []*ContestProblem {
	if x != nil {
		return x.LowestProblem
	}
	return nil
}

func (x *ContestFinishStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContestFinishStatus) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type QueryContestFinishStatusRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // 返回信息
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`      // 返回码
	Contest       []*ContestFinishStatus `protobuf:"bytes,3,rep,name=contest,proto3" json:"contest,omitempty"` // 作业完成情况
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`    // 总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryContestFinishStatusRsp) Reset() {
	*x = QueryContestFinishStatusRsp{}
	mi := &file_contest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryContestFinishStatusRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryContestFinishStatusRsp) ProtoMessage() {}

func (x *QueryContestFinishStatusRsp) ProtoReflect() protoreflect.Message {
	mi := &file_contest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryContestFinishStatusRsp.ProtoReflect.Descriptor instead.
func (*QueryContestFinishStatusRsp) Descriptor() ([]byte, []int) {
	return file_contest_proto_rawDescGZIP(), []int{1}
}

func (x *QueryContestFinishStatusRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *QueryContestFinishStatusRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *QueryContestFinishStatusRsp) GetContest() []*ContestFinishStatus {
	if x != nil {
		return x.Contest
	}
	return nil
}

func (x *QueryContestFinishStatusRsp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type QueryContestFinishCountRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`            // 返回信息
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`                 // 返回码
	FinishCount   int32                  `protobuf:"varint,3,opt,name=finishCount,proto3" json:"finishCount,omitempty"`   // 完成数
	ProblemCount  int32                  `protobuf:"varint,4,opt,name=problemCount,proto3" json:"problemCount,omitempty"` // 题目数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryContestFinishCountRsp) Reset() {
	*x = QueryContestFinishCountRsp{}
	mi := &file_contest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryContestFinishCountRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryContestFinishCountRsp) ProtoMessage() {}

func (x *QueryContestFinishCountRsp) ProtoReflect() protoreflect.Message {
	mi := &file_contest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryContestFinishCountRsp.ProtoReflect.Descriptor instead.
func (*QueryContestFinishCountRsp) Descriptor() ([]byte, []int) {
	return file_contest_proto_rawDescGZIP(), []int{2}
}

func (x *QueryContestFinishCountRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *QueryContestFinishCountRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *QueryContestFinishCountRsp) GetFinishCount() int32 {
	if x != nil {
		return x.FinishCount
	}
	return 0
}

func (x *QueryContestFinishCountRsp) GetProblemCount() int32 {
	if x != nil {
		return x.ProblemCount
	}
	return 0
}

type QueryContestLanguageMaskRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`           // 返回信息
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`                // 返回码
	LanguageMask  string                 `protobuf:"bytes,3,opt,name=languageMask,proto3" json:"languageMask,omitempty"` //  语言列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryContestLanguageMaskRsp) Reset() {
	*x = QueryContestLanguageMaskRsp{}
	mi := &file_contest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryContestLanguageMaskRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryContestLanguageMaskRsp) ProtoMessage() {}

func (x *QueryContestLanguageMaskRsp) ProtoReflect() protoreflect.Message {
	mi := &file_contest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryContestLanguageMaskRsp.ProtoReflect.Descriptor instead.
func (*QueryContestLanguageMaskRsp) Descriptor() ([]byte, []int) {
	return file_contest_proto_rawDescGZIP(), []int{3}
}

func (x *QueryContestLanguageMaskRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *QueryContestLanguageMaskRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *QueryContestLanguageMaskRsp) GetLanguageMask() string {
	if x != nil {
		return x.LanguageMask
	}
	return ""
}

type QueryContestPrivilegeInfoRsp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Message        string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`               // 返回信息
	Code           int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`                    // 返回码
	ContestProblem string                 `protobuf:"bytes,3,opt,name=contestProblem,proto3" json:"contestProblem,omitempty"` // 查询作业的问题
	ContestUser    string                 `protobuf:"bytes,4,opt,name=contestUser,proto3" json:"contestUser,omitempty"`       // 查询作业的用户
	Private        int32                  `protobuf:"varint,5,opt,name=private,proto3" json:"private,omitempty"`              // 作业的可见度
	ContestClass   string                 `protobuf:"bytes,6,opt,name=contestClass,proto3" json:"contestClass,omitempty"`     // 查询作业的班级
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QueryContestPrivilegeInfoRsp) Reset() {
	*x = QueryContestPrivilegeInfoRsp{}
	mi := &file_contest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryContestPrivilegeInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryContestPrivilegeInfoRsp) ProtoMessage() {}

func (x *QueryContestPrivilegeInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_contest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryContestPrivilegeInfoRsp.ProtoReflect.Descriptor instead.
func (*QueryContestPrivilegeInfoRsp) Descriptor() ([]byte, []int) {
	return file_contest_proto_rawDescGZIP(), []int{4}
}

func (x *QueryContestPrivilegeInfoRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *QueryContestPrivilegeInfoRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *QueryContestPrivilegeInfoRsp) GetContestProblem() string {
	if x != nil {
		return x.ContestProblem
	}
	return ""
}

func (x *QueryContestPrivilegeInfoRsp) GetContestUser() string {
	if x != nil {
		return x.ContestUser
	}
	return ""
}

func (x *QueryContestPrivilegeInfoRsp) GetPrivate() int32 {
	if x != nil {
		return x.Private
	}
	return 0
}

func (x *QueryContestPrivilegeInfoRsp) GetContestClass() string {
	if x != nil {
		return x.ContestClass
	}
	return ""
}

type AddContestReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int32                  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`            // 用户编号
	StartTime     string                 `protobuf:"bytes,2,opt,name=startTime,proto3" json:"startTime,omitempty"`       // 开始时间
	EndTime       string                 `protobuf:"bytes,3,opt,name=endTime,proto3" json:"endTime,omitempty"`           // 结束时间
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`               // 标题
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`   // 描述
	Private       int32                  `protobuf:"varint,6,opt,name=private,proto3" json:"private,omitempty"`          // 是否私有，0公开，1班级访问，2密码访问
	Password      string                 `protobuf:"bytes,7,opt,name=password,proto3" json:"password,omitempty"`         // 密码
	LanguageMask  string                 `protobuf:"bytes,8,opt,name=languageMask,proto3" json:"languageMask,omitempty"` // 限制语言
	Problems      string                 `protobuf:"bytes,9,opt,name=problems,proto3" json:"problems,omitempty"`         // 题目列表
	People        string                 `protobuf:"bytes,10,opt,name=people,proto3" json:"people,omitempty"`            // 人员
	ClassID       string                 `protobuf:"bytes,11,opt,name=classID,proto3" json:"classID,omitempty"`          // 班级
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddContestReq) Reset() {
	*x = AddContestReq{}
	mi := &file_contest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddContestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddContestReq) ProtoMessage() {}

func (x *AddContestReq) ProtoReflect() protoreflect.Message {
	mi := &file_contest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddContestReq.ProtoReflect.Descriptor instead.
func (*AddContestReq) Descriptor() ([]byte, []int) {
	return file_contest_proto_rawDescGZIP(), []int{5}
}

func (x *AddContestReq) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *AddContestReq) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *AddContestReq) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *AddContestReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddContestReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddContestReq) GetPrivate() int32 {
	if x != nil {
		return x.Private
	}
	return 0
}

func (x *AddContestReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AddContestReq) GetLanguageMask() string {
	if x != nil {
		return x.LanguageMask
	}
	return ""
}

func (x *AddContestReq) GetProblems() string {
	if x != nil {
		return x.Problems
	}
	return ""
}

func (x *AddContestReq) GetPeople() string {
	if x != nil {
		return x.People
	}
	return ""
}

func (x *AddContestReq) GetClassID() string {
	if x != nil {
		return x.ClassID
	}
	return ""
}

type UpdateContestReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContestID     int32                  `protobuf:"varint,1,opt,name=contestID,proto3" json:"contestID,omitempty"`      // 作业编号
	UserID        int32                  `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`            // 用户编号
	StartTime     string                 `protobuf:"bytes,3,opt,name=startTime,proto3" json:"startTime,omitempty"`       // 开始时间
	EndTime       string                 `protobuf:"bytes,4,opt,name=endTime,proto3" json:"endTime,omitempty"`           // 结束时间
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`               // 标题
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`   // 描述
	Private       int32                  `protobuf:"varint,7,opt,name=private,proto3" json:"private,omitempty"`          // 是否私有，0公开，1班级访问，2密码访问
	Password      string                 `protobuf:"bytes,8,opt,name=password,proto3" json:"password,omitempty"`         // 密码
	LanguageMask  string                 `protobuf:"bytes,9,opt,name=languageMask,proto3" json:"languageMask,omitempty"` // 限制语言
	Problems      string                 `protobuf:"bytes,10,opt,name=problems,proto3" json:"problems,omitempty"`        // 题目列表
	People        string                 `protobuf:"bytes,11,opt,name=people,proto3" json:"people,omitempty"`            // 人员
	ClassID       string                 `protobuf:"bytes,12,opt,name=classID,proto3" json:"classID,omitempty"`          // 班级
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateContestReq) Reset() {
	*x = UpdateContestReq{}
	mi := &file_contest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContestReq) ProtoMessage() {}

func (x *UpdateContestReq) ProtoReflect() protoreflect.Message {
	mi := &file_contest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContestReq.ProtoReflect.Descriptor instead.
func (*UpdateContestReq) Descriptor() ([]byte, []int) {
	return file_contest_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateContestReq) GetContestID() int32 {
	if x != nil {
		return x.ContestID
	}
	return 0
}

func (x *UpdateContestReq) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *UpdateContestReq) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *UpdateContestReq) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *UpdateContestReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateContestReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateContestReq) GetPrivate() int32 {
	if x != nil {
		return x.Private
	}
	return 0
}

func (x *UpdateContestReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UpdateContestReq) GetLanguageMask() string {
	if x != nil {
		return x.LanguageMask
	}
	return ""
}

func (x *UpdateContestReq) GetProblems() string {
	if x != nil {
		return x.Problems
	}
	return ""
}

func (x *UpdateContestReq) GetPeople() string {
	if x != nil {
		return x.People
	}
	return ""
}

func (x *UpdateContestReq) GetClassID() string {
	if x != nil {
		return x.ClassID
	}
	return ""
}

type UpdateContestStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int32                  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`       // 用户主键
	ContestID     int32                  `protobuf:"varint,2,opt,name=contestID,proto3" json:"contestID,omitempty"` // 作业主键
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`       // 状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateContestStatusReq) Reset() {
	*x = UpdateContestStatusReq{}
	mi := &file_contest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContestStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContestStatusReq) ProtoMessage() {}

func (x *UpdateContestStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_contest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContestStatusReq.ProtoReflect.Descriptor instead.
func (*UpdateContestStatusReq) Descriptor() ([]byte, []int) {
	return file_contest_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateContestStatusReq) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *UpdateContestStatusReq) GetContestID() int32 {
	if x != nil {
		return x.ContestID
	}
	return 0
}

func (x *UpdateContestStatusReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type QueryContestListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`           // 页
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`         // 页大小
	UserID        int32                  `protobuf:"varint,3,opt,name=userID,proto3" json:"userID,omitempty"`       // 用户主键
	QueryType     int32                  `protobuf:"varint,4,opt,name=queryType,proto3" json:"queryType,omitempty"` // 查询的类型
	ClassID       string                 `protobuf:"bytes,5,opt,name=classID,proto3" json:"classID,omitempty"`      // 班级编号
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`            // 作业名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryContestListReq) Reset() {
	*x = QueryContestListReq{}
	mi := &file_contest_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryContestListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryContestListReq) ProtoMessage() {}

func (x *QueryContestListReq) ProtoReflect() protoreflect.Message {
	mi := &file_contest_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryContestListReq.ProtoReflect.Descriptor instead.
func (*QueryContestListReq) Descriptor() ([]byte, []int) {
	return file_contest_proto_rawDescGZIP(), []int{8}
}

func (x *QueryContestListReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *QueryContestListReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryContestListReq) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *QueryContestListReq) GetQueryType() int32 {
	if x != nil {
		return x.QueryType
	}
	return 0
}

func (x *QueryContestListReq) GetClassID() string {
	if x != nil {
		return x.ClassID
	}
	return ""
}

func (x *QueryContestListReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type QueryContestListRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`              // 返回信息
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`                   // 返回码
	Contests      []*Contest             `protobuf:"bytes,3,rep,name=contests,proto3" json:"contests,omitempty"`            // 作业集合
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`                 // 总数
	EndCount      int32                  `protobuf:"varint,5,opt,name=EndCount,proto3" json:"EndCount,omitempty"`           // 已经结束
	NotStartCount int32                  `protobuf:"varint,6,opt,name=notStartCount,proto3" json:"notStartCount,omitempty"` // 未开始
	RunningCount  int32                  `protobuf:"varint,7,opt,name=runningCount,proto3" json:"runningCount,omitempty"`   // 进行中
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryContestListRsp) Reset() {
	*x = QueryContestListRsp{}
	mi := &file_contest_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryContestListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryContestListRsp) ProtoMessage() {}

func (x *QueryContestListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_contest_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryContestListRsp.ProtoReflect.Descriptor instead.
func (*QueryContestListRsp) Descriptor() ([]byte, []int) {
	return file_contest_proto_rawDescGZIP(), []int{9}
}

func (x *QueryContestListRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *QueryContestListRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *QueryContestListRsp) GetContests() []*Contest {
	if x != nil {
		return x.Contests
	}
	return nil
}

func (x *QueryContestListRsp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *QueryContestListRsp) GetEndCount() int32 {
	if x != nil {
		return x.EndCount
	}
	return 0
}

func (x *QueryContestListRsp) GetNotStartCount() int32 {
	if x != nil {
		return x.NotStartCount
	}
	return 0
}

func (x *QueryContestListRsp) GetRunningCount() int32 {
	if x != nil {
		return x.RunningCount
	}
	return 0
}

type QueryContestReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContestID     int32                  `protobuf:"varint,1,opt,name=contestID,proto3" json:"contestID,omitempty"` // 作业编号
	UserID        int32                  `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`       // 用户主键
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`    // 密码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryContestReq) Reset() {
	*x = QueryContestReq{}
	mi := &file_contest_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryContestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryContestReq) ProtoMessage() {}

func (x *QueryContestReq) ProtoReflect() protoreflect.Message {
	mi := &file_contest_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryContestReq.ProtoReflect.Descriptor instead.
func (*QueryContestReq) Descriptor() ([]byte, []int) {
	return file_contest_proto_rawDescGZIP(), []int{10}
}

func (x *QueryContestReq) GetContestID() int32 {
	if x != nil {
		return x.ContestID
	}
	return 0
}

func (x *QueryContestReq) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *QueryContestReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type QueryContestRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // 返回信息
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`      // 返回码
	Contest       *Contest               `protobuf:"bytes,3,opt,name=contest,proto3" json:"contest,omitempty"` // 作业
	See           bool                   `protobuf:"varint,4,opt,name=see,proto3" json:"see,omitempty"`        // 是否可见
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryContestRsp) Reset() {
	*x = QueryContestRsp{}
	mi := &file_contest_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryContestRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryContestRsp) ProtoMessage() {}

func (x *QueryContestRsp) ProtoReflect() protoreflect.Message {
	mi := &file_contest_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryContestRsp.ProtoReflect.Descriptor instead.
func (*QueryContestRsp) Descriptor() ([]byte, []int) {
	return file_contest_proto_rawDescGZIP(), []int{11}
}

func (x *QueryContestRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *QueryContestRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *QueryContestRsp) GetContest() *Contest {
	if x != nil {
		return x.Contest
	}
	return nil
}

func (x *QueryContestRsp) GetSee() bool {
	if x != nil {
		return x.See
	}
	return false
}

type Contest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContestID     int32                  `protobuf:"varint,1,opt,name=contestID,proto3" json:"contestID,omitempty"`        // 作业编号
	StartTime     string                 `protobuf:"bytes,2,opt,name=startTime,proto3" json:"startTime,omitempty"`         // 开始时间
	EndTime       string                 `protobuf:"bytes,3,opt,name=endTime,proto3" json:"endTime,omitempty"`             // 结束时间
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`                 // 标题
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`     // 描述
	LanguageMask  string                 `protobuf:"bytes,6,opt,name=languageMask,proto3" json:"languageMask,omitempty"`   // 限制语言
	Creator       string                 `protobuf:"bytes,7,opt,name=creator,proto3" json:"creator,omitempty"`             // 创建者
	Problems      []*ContestProblem      `protobuf:"bytes,8,rep,name=problems,proto3" json:"problems,omitempty"`           // 题目列表
	CreatedBy     int32                  `protobuf:"varint,9,opt,name=createdBy,proto3" json:"createdBy,omitempty"`        // 创建者编号
	Private       int32                  `protobuf:"varint,10,opt,name=private,proto3" json:"private,omitempty"`           // 是否私有
	Password      string                 `protobuf:"bytes,11,opt,name=password,proto3" json:"password,omitempty"`          // 密码
	Enable        int32                  `protobuf:"varint,12,opt,name=enable,proto3" json:"enable,omitempty"`             // 是否结束
	Classes       []*Class               `protobuf:"bytes,13,rep,name=classes,proto3" json:"classes,omitempty"`            // 作业的班级
	Participants  int32                  `protobuf:"varint,14,opt,name=participants,proto3" json:"participants,omitempty"` // 参与人数
	CanUpdate     int32                  `protobuf:"varint,15,opt,name=canUpdate,proto3" json:"canUpdate,omitempty"`       // 是否能被更新
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contest) Reset() {
	*x = Contest{}
	mi := &file_contest_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contest) ProtoMessage() {}

func (x *Contest) ProtoReflect() protoreflect.Message {
	mi := &file_contest_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contest.ProtoReflect.Descriptor instead.
func (*Contest) Descriptor() ([]byte, []int) {
	return file_contest_proto_rawDescGZIP(), []int{12}
}

func (x *Contest) GetContestID() int32 {
	if x != nil {
		return x.ContestID
	}
	return 0
}

func (x *Contest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *Contest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *Contest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Contest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Contest) GetLanguageMask() string {
	if x != nil {
		return x.LanguageMask
	}
	return ""
}

func (x *Contest) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *Contest) GetProblems() []*ContestProblem {
	if x != nil {
		return x.Problems
	}
	return nil
}

func (x *Contest) GetCreatedBy() int32 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *Contest) GetPrivate() int32 {
	if x != nil {
		return x.Private
	}
	return 0
}

func (x *Contest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Contest) GetEnable() int32 {
	if x != nil {
		return x.Enable
	}
	return 0
}

func (x *Contest) GetClasses() []*Class {
	if x != nil {
		return x.Classes
	}
	return nil
}

func (x *Contest) GetParticipants() int32 {
	if x != nil {
		return x.Participants
	}
	return 0
}

func (x *Contest) GetCanUpdate() int32 {
	if x != nil {
		return x.CanUpdate
	}
	return 0
}

type Class struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassID       int32                  `protobuf:"varint,1,opt,name=classID,proto3" json:"classID,omitempty"`    // 班级编号
	ClassName     string                 `protobuf:"bytes,2,opt,name=ClassName,proto3" json:"ClassName,omitempty"` // 班级名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Class) Reset() {
	*x = Class{}
	mi := &file_contest_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Class) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Class) ProtoMessage() {}

func (x *Class) ProtoReflect() protoreflect.Message {
	mi := &file_contest_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Class.ProtoReflect.Descriptor instead.
func (*Class) Descriptor() ([]byte, []int) {
	return file_contest_proto_rawDescGZIP(), []int{13}
}

func (x *Class) GetClassID() int32 {
	if x != nil {
		return x.ClassID
	}
	return 0
}

func (x *Class) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

type CommonRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // 返回信息
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`      // 返回码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonRsp) Reset() {
	*x = CommonRsp{}
	mi := &file_contest_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonRsp) ProtoMessage() {}

func (x *CommonRsp) ProtoReflect() protoreflect.Message {
	mi := &file_contest_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonRsp.ProtoReflect.Descriptor instead.
func (*CommonRsp) Descriptor() ([]byte, []int) {
	return file_contest_proto_rawDescGZIP(), []int{14}
}

func (x *CommonRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommonRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type ContestProblem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProblemID     int32                  `protobuf:"varint,1,opt,name=problemID,proto3" json:"problemID,omitempty"`    // 题目编号
	ProblemName   string                 `protobuf:"bytes,2,opt,name=problemName,proto3" json:"problemName,omitempty"` // 题目名称
	IsDone        int32                  `protobuf:"varint,3,opt,name=isDone,proto3" json:"isDone,omitempty"`          // 是否做完
	Solved        int32                  `protobuf:"varint,4,opt,name=solved,proto3" json:"solved,omitempty"`          // 解决
	Submission    int32                  `protobuf:"varint,5,opt,name=submission,proto3" json:"submission,omitempty"`  // 提交
	Difficulty    int32                  `protobuf:"varint,6,opt,name=difficulty,proto3" json:"difficulty,omitempty"`  // 难度
	Score         int32                  `protobuf:"varint,7,opt,name=score,proto3" json:"score,omitempty"`            // 得分
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContestProblem) Reset() {
	*x = ContestProblem{}
	mi := &file_contest_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContestProblem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContestProblem) ProtoMessage() {}

func (x *ContestProblem) ProtoReflect() protoreflect.Message {
	mi := &file_contest_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContestProblem.ProtoReflect.Descriptor instead.
func (*ContestProblem) Descriptor() ([]byte, []int) {
	return file_contest_proto_rawDescGZIP(), []int{15}
}

func (x *ContestProblem) GetProblemID() int32 {
	if x != nil {
		return x.ProblemID
	}
	return 0
}

func (x *ContestProblem) GetProblemName() string {
	if x != nil {
		return x.ProblemName
	}
	return ""
}

func (x *ContestProblem) GetIsDone() int32 {
	if x != nil {
		return x.IsDone
	}
	return 0
}

func (x *ContestProblem) GetSolved() int32 {
	if x != nil {
		return x.Solved
	}
	return 0
}

func (x *ContestProblem) GetSubmission() int32 {
	if x != nil {
		return x.Submission
	}
	return 0
}

func (x *ContestProblem) GetDifficulty() int32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *ContestProblem) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_contest_proto protoreflect.FileDescriptor

const file_contest_proto_rawDesc = "" +
	"\n" +
	"\rcontest.proto\x12\n" +
	"oj.contest\"\xf7\x01\n" +
	"\x13ContestFinishStatus\x12 \n" +
	"\vfinishCount\x18\x01 \x01(\x05R\vfinishCount\x12\"\n" +
	"\fparticipants\x18\x02 \x01(\x05R\fparticipants\x12*\n" +
	"\x10needParticipants\x18\x03 \x01(\x05R\x10needParticipants\x12@\n" +
	"\rlowestProblem\x18\x04 \x03(\v2\x1a.oj.contest.ContestProblemR\rlowestProblem\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x18\n" +
	"\aendTime\x18\x06 \x01(\tR\aendTime\"\x9c\x01\n" +
	"\x1bQueryContestFinishStatusRsp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x129\n" +
	"\acontest\x18\x03 \x03(\v2\x1f.oj.contest.ContestFinishStatusR\acontest\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\"\x90\x01\n" +
	"\x1aQueryContestFinishCountRsp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12 \n" +
	"\vfinishCount\x18\x03 \x01(\x05R\vfinishCount\x12\"\n" +
	"\fproblemCount\x18\x04 \x01(\x05R\fproblemCount\"o\n" +
	"\x1bQueryContestLanguageMaskRsp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\"\n" +
	"\flanguageMask\x18\x03 \x01(\tR\flanguageMask\"\xd4\x01\n" +
	"\x1cQueryContestPrivilegeInfoRsp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12&\n" +
	"\x0econtestProblem\x18\x03 \x01(\tR\x0econtestProblem\x12 \n" +
	"\vcontestUser\x18\x04 \x01(\tR\vcontestUser\x12\x18\n" +
	"\aprivate\x18\x05 \x01(\x05R\aprivate\x12\"\n" +
	"\fcontestClass\x18\x06 \x01(\tR\fcontestClass\"\xbf\x02\n" +
	"\rAddContestReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x05R\x06userID\x12\x1c\n" +
	"\tstartTime\x18\x02 \x01(\tR\tstartTime\x12\x18\n" +
	"\aendTime\x18\x03 \x01(\tR\aendTime\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x18\n" +
	"\aprivate\x18\x06 \x01(\x05R\aprivate\x12\x1a\n" +
	"\bpassword\x18\a \x01(\tR\bpassword\x12\"\n" +
	"\flanguageMask\x18\b \x01(\tR\flanguageMask\x12\x1a\n" +
	"\bproblems\x18\t \x01(\tR\bproblems\x12\x16\n" +
	"\x06people\x18\n" +
	" \x01(\tR\x06people\x12\x18\n" +
	"\aclassID\x18\v \x01(\tR\aclassID\"\xe0\x02\n" +
	"\x10UpdateContestReq\x12\x1c\n" +
	"\tcontestID\x18\x01 \x01(\x05R\tcontestID\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\x05R\x06userID\x12\x1c\n" +
	"\tstartTime\x18\x03 \x01(\tR\tstartTime\x12\x18\n" +
	"\aendTime\x18\x04 \x01(\tR\aendTime\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x18\n" +
	"\aprivate\x18\a \x01(\x05R\aprivate\x12\x1a\n" +
	"\bpassword\x18\b \x01(\tR\bpassword\x12\"\n" +
	"\flanguageMask\x18\t \x01(\tR\flanguageMask\x12\x1a\n" +
	"\bproblems\x18\n" +
	" \x01(\tR\bproblems\x12\x16\n" +
	"\x06people\x18\v \x01(\tR\x06people\x12\x18\n" +
	"\aclassID\x18\f \x01(\tR\aclassID\"f\n" +
	"\x16UpdateContestStatusReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x05R\x06userID\x12\x1c\n" +
	"\tcontestID\x18\x02 \x01(\x05R\tcontestID\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\"\xa3\x01\n" +
	"\x13QueryContestListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06userID\x18\x03 \x01(\x05R\x06userID\x12\x1c\n" +
	"\tqueryType\x18\x04 \x01(\x05R\tqueryType\x12\x18\n" +
	"\aclassID\x18\x05 \x01(\tR\aclassID\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\"\xf0\x01\n" +
	"\x13QueryContestListRsp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12/\n" +
	"\bcontests\x18\x03 \x03(\v2\x13.oj.contest.ContestR\bcontests\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\x12\x1a\n" +
	"\bEndCount\x18\x05 \x01(\x05R\bEndCount\x12$\n" +
	"\rnotStartCount\x18\x06 \x01(\x05R\rnotStartCount\x12\"\n" +
	"\frunningCount\x18\a \x01(\x05R\frunningCount\"c\n" +
	"\x0fQueryContestReq\x12\x1c\n" +
	"\tcontestID\x18\x01 \x01(\x05R\tcontestID\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\x05R\x06userID\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"\x80\x01\n" +
	"\x0fQueryContestRsp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12-\n" +
	"\acontest\x18\x03 \x01(\v2\x13.oj.contest.ContestR\acontest\x12\x10\n" +
	"\x03see\x18\x04 \x01(\bR\x03see\"\xe8\x03\n" +
	"\aContest\x12\x1c\n" +
	"\tcontestID\x18\x01 \x01(\x05R\tcontestID\x12\x1c\n" +
	"\tstartTime\x18\x02 \x01(\tR\tstartTime\x12\x18\n" +
	"\aendTime\x18\x03 \x01(\tR\aendTime\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\"\n" +
	"\flanguageMask\x18\x06 \x01(\tR\flanguageMask\x12\x18\n" +
	"\acreator\x18\a \x01(\tR\acreator\x126\n" +
	"\bproblems\x18\b \x03(\v2\x1a.oj.contest.ContestProblemR\bproblems\x12\x1c\n" +
	"\tcreatedBy\x18\t \x01(\x05R\tcreatedBy\x12\x18\n" +
	"\aprivate\x18\n" +
	" \x01(\x05R\aprivate\x12\x1a\n" +
	"\bpassword\x18\v \x01(\tR\bpassword\x12\x16\n" +
	"\x06enable\x18\f \x01(\x05R\x06enable\x12+\n" +
	"\aclasses\x18\r \x03(\v2\x11.oj.contest.ClassR\aclasses\x12\"\n" +
	"\fparticipants\x18\x0e \x01(\x05R\fparticipants\x12\x1c\n" +
	"\tcanUpdate\x18\x0f \x01(\x05R\tcanUpdate\"?\n" +
	"\x05Class\x12\x18\n" +
	"\aclassID\x18\x01 \x01(\x05R\aclassID\x12\x1c\n" +
	"\tClassName\x18\x02 \x01(\tR\tClassName\"9\n" +
	"\tCommonRsp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\"\xd6\x01\n" +
	"\x0eContestProblem\x12\x1c\n" +
	"\tproblemID\x18\x01 \x01(\x05R\tproblemID\x12 \n" +
	"\vproblemName\x18\x02 \x01(\tR\vproblemName\x12\x16\n" +
	"\x06isDone\x18\x03 \x01(\x05R\x06isDone\x12\x16\n" +
	"\x06solved\x18\x04 \x01(\x05R\x06solved\x12\x1e\n" +
	"\n" +
	"submission\x18\x05 \x01(\x05R\n" +
	"submission\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x06 \x01(\x05R\n" +
	"difficulty\x12\x14\n" +
	"\x05score\x18\a \x01(\x05R\x05score2\xff\x06\n" +
	"\rContestServer\x12J\n" +
	"\fQueryContest\x12\x1b.oj.contest.QueryContestReq\x1a\x1b.oj.contest.QueryContestRsp\"\x00\x12V\n" +
	"\x10QueryContestList\x12\x1f.oj.contest.QueryContestListReq\x1a\x1f.oj.contest.QueryContestListRsp\"\x00\x12X\n" +
	"\x12QueryMyContestList\x12\x1f.oj.contest.QueryContestListReq\x1a\x1f.oj.contest.QueryContestListRsp\"\x00\x12R\n" +
	"\x13UpdateContestStatus\x12\".oj.contest.UpdateContestStatusReq\x1a\x15.oj.contest.CommonRsp\"\x00\x12@\n" +
	"\n" +
	"AddContest\x12\x19.oj.contest.AddContestReq\x1a\x15.oj.contest.CommonRsp\"\x00\x12F\n" +
	"\rUpdateContest\x12\x1c.oj.contest.UpdateContestReq\x1a\x15.oj.contest.CommonRsp\"\x00\x12d\n" +
	"\x19QueryContestPrivilegeInfo\x12\x1b.oj.contest.QueryContestReq\x1a(.oj.contest.QueryContestPrivilegeInfoRsp\"\x00\x12b\n" +
	"\x18QueryContestLanguageMask\x12\x1b.oj.contest.QueryContestReq\x1a'.oj.contest.QueryContestLanguageMaskRsp\"\x00\x12`\n" +
	"\x17QueryContestFinishCount\x12\x1b.oj.contest.QueryContestReq\x1a&.oj.contest.QueryContestFinishCountRsp\"\x00\x12f\n" +
	"\x18QueryContestFinishStatus\x12\x1f.oj.contest.QueryContestListReq\x1a'.oj.contest.QueryContestFinishStatusRsp\"\x00B(Z&github.com/csuJudge/judgeProto/contestb\x06proto3"

var (
	file_contest_proto_rawDescOnce sync.Once
	file_contest_proto_rawDescData []byte
)

func file_contest_proto_rawDescGZIP() []byte {
	file_contest_proto_rawDescOnce.Do(func() {
		file_contest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contest_proto_rawDesc), len(file_contest_proto_rawDesc)))
	})
	return file_contest_proto_rawDescData
}

var file_contest_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_contest_proto_goTypes = []any{
	(*ContestFinishStatus)(nil),          // 0: oj.contest.ContestFinishStatus
	(*QueryContestFinishStatusRsp)(nil),  // 1: oj.contest.QueryContestFinishStatusRsp
	(*QueryContestFinishCountRsp)(nil),   // 2: oj.contest.QueryContestFinishCountRsp
	(*QueryContestLanguageMaskRsp)(nil),  // 3: oj.contest.QueryContestLanguageMaskRsp
	(*QueryContestPrivilegeInfoRsp)(nil), // 4: oj.contest.QueryContestPrivilegeInfoRsp
	(*AddContestReq)(nil),                // 5: oj.contest.AddContestReq
	(*UpdateContestReq)(nil),             // 6: oj.contest.UpdateContestReq
	(*UpdateContestStatusReq)(nil),       // 7: oj.contest.UpdateContestStatusReq
	(*QueryContestListReq)(nil),          // 8: oj.contest.QueryContestListReq
	(*QueryContestListRsp)(nil),          // 9: oj.contest.QueryContestListRsp
	(*QueryContestReq)(nil),              // 10: oj.contest.QueryContestReq
	(*QueryContestRsp)(nil),              // 11: oj.contest.QueryContestRsp
	(*Contest)(nil),                      // 12: oj.contest.Contest
	(*Class)(nil),                        // 13: oj.contest.Class
	(*CommonRsp)(nil),                    // 14: oj.contest.CommonRsp
	(*ContestProblem)(nil),               // 15: oj.contest.ContestProblem
}
var file_contest_proto_depIdxs = []int32{
	15, // 0: oj.contest.ContestFinishStatus.lowestProblem:type_name -> oj.contest.ContestProblem
	0,  // 1: oj.contest.QueryContestFinishStatusRsp.contest:type_name -> oj.contest.ContestFinishStatus
	12, // 2: oj.contest.QueryContestListRsp.contests:type_name -> oj.contest.Contest
	12, // 3: oj.contest.QueryContestRsp.contest:type_name -> oj.contest.Contest
	15, // 4: oj.contest.Contest.problems:type_name -> oj.contest.ContestProblem
	13, // 5: oj.contest.Contest.classes:type_name -> oj.contest.Class
	10, // 6: oj.contest.ContestServer.QueryContest:input_type -> oj.contest.QueryContestReq
	8,  // 7: oj.contest.ContestServer.QueryContestList:input_type -> oj.contest.QueryContestListReq
	8,  // 8: oj.contest.ContestServer.QueryMyContestList:input_type -> oj.contest.QueryContestListReq
	7,  // 9: oj.contest.ContestServer.UpdateContestStatus:input_type -> oj.contest.UpdateContestStatusReq
	5,  // 10: oj.contest.ContestServer.AddContest:input_type -> oj.contest.AddContestReq
	6,  // 11: oj.contest.ContestServer.UpdateContest:input_type -> oj.contest.UpdateContestReq
	10, // 12: oj.contest.ContestServer.QueryContestPrivilegeInfo:input_type -> oj.contest.QueryContestReq
	10, // 13: oj.contest.ContestServer.QueryContestLanguageMask:input_type -> oj.contest.QueryContestReq
	10, // 14: oj.contest.ContestServer.QueryContestFinishCount:input_type -> oj.contest.QueryContestReq
	8,  // 15: oj.contest.ContestServer.QueryContestFinishStatus:input_type -> oj.contest.QueryContestListReq
	11, // 16: oj.contest.ContestServer.QueryContest:output_type -> oj.contest.QueryContestRsp
	9,  // 17: oj.contest.ContestServer.QueryContestList:output_type -> oj.contest.QueryContestListRsp
	9,  // 18: oj.contest.ContestServer.QueryMyContestList:output_type -> oj.contest.QueryContestListRsp
	14, // 19: oj.contest.ContestServer.UpdateContestStatus:output_type -> oj.contest.CommonRsp
	14, // 20: oj.contest.ContestServer.AddContest:output_type -> oj.contest.CommonRsp
	14, // 21: oj.contest.ContestServer.UpdateContest:output_type -> oj.contest.CommonRsp
	4,  // 22: oj.contest.ContestServer.QueryContestPrivilegeInfo:output_type -> oj.contest.QueryContestPrivilegeInfoRsp
	3,  // 23: oj.contest.ContestServer.QueryContestLanguageMask:output_type -> oj.contest.QueryContestLanguageMaskRsp
	2,  // 24: oj.contest.ContestServer.QueryContestFinishCount:output_type -> oj.contest.QueryContestFinishCountRsp
	1,  // 25: oj.contest.ContestServer.QueryContestFinishStatus:output_type -> oj.contest.QueryContestFinishStatusRsp
	16, // [16:26] is the sub-list for method output_type
	6,  // [6:16] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_contest_proto_init() }
func file_contest_proto_init() {
	if File_contest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contest_proto_rawDesc), len(file_contest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contest_proto_goTypes,
		DependencyIndexes: file_contest_proto_depIdxs,
		MessageInfos:      file_contest_proto_msgTypes,
	}.Build()
	File_contest_proto = out.File
	file_contest_proto_goTypes = nil
	file_contest_proto_depIdxs = nil
}
