// Code generated by MockGen. DO NOT EDIT.
// Source: stub/github.com/csuJudge/judgeProto/captcha/captcha.trpc.go
//
// Generated by this command:
//
//	mockgen -destination=stub/github.com/csuJudge/judgeProto/captcha/captcha_mock.go -package=captcha -self_package=github.com/csuJudge/judgeProto/captcha --source=stub/github.com/csuJudge/judgeProto/captcha/captcha.trpc.go
//

// Package captcha is a generated GoMock package.
package captcha

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	client "trpc.group/trpc-go/trpc-go/client"
)

// MockCaptchaServerService is a mock of CaptchaServerService interface.
type MockCaptchaServerService struct {
	ctrl     *gomock.Controller
	recorder *MockCaptchaServerServiceMockRecorder
}

// MockCaptchaServerServiceMockRecorder is the mock recorder for MockCaptchaServerService.
type MockCaptchaServerServiceMockRecorder struct {
	mock *MockCaptchaServerService
}

// NewMockCaptchaServerService creates a new mock instance.
func NewMockCaptchaServerService(ctrl *gomock.Controller) *MockCaptchaServerService {
	mock := &MockCaptchaServerService{ctrl: ctrl}
	mock.recorder = &MockCaptchaServerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCaptchaServerService) EXPECT() *MockCaptchaServerServiceMockRecorder {
	return m.recorder
}

// ISGOMOCK indicates that this struct is a gomock mock.
func (m *MockCaptchaServerService) ISGOMOCK() struct{} {
	return struct{}{}
}

// SendCaptcha mocks base method.
func (m *MockCaptchaServerService) SendCaptcha(ctx context.Context, req *SendCaptchaReq) (*SendCaptchaRsp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendCaptcha", ctx, req)
	ret0, _ := ret[0].(*SendCaptchaRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendCaptcha indicates an expected call of SendCaptcha.
func (mr *MockCaptchaServerServiceMockRecorder) SendCaptcha(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendCaptcha", reflect.TypeOf((*MockCaptchaServerService)(nil).SendCaptcha), ctx, req)
}

// MockCaptchaServerClientProxy is a mock of CaptchaServerClientProxy interface.
type MockCaptchaServerClientProxy struct {
	ctrl     *gomock.Controller
	recorder *MockCaptchaServerClientProxyMockRecorder
}

// MockCaptchaServerClientProxyMockRecorder is the mock recorder for MockCaptchaServerClientProxy.
type MockCaptchaServerClientProxyMockRecorder struct {
	mock *MockCaptchaServerClientProxy
}

// NewMockCaptchaServerClientProxy creates a new mock instance.
func NewMockCaptchaServerClientProxy(ctrl *gomock.Controller) *MockCaptchaServerClientProxy {
	mock := &MockCaptchaServerClientProxy{ctrl: ctrl}
	mock.recorder = &MockCaptchaServerClientProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCaptchaServerClientProxy) EXPECT() *MockCaptchaServerClientProxyMockRecorder {
	return m.recorder
}

// ISGOMOCK indicates that this struct is a gomock mock.
func (m *MockCaptchaServerClientProxy) ISGOMOCK() struct{} {
	return struct{}{}
}

// SendCaptcha mocks base method.
func (m *MockCaptchaServerClientProxy) SendCaptcha(ctx context.Context, req *SendCaptchaReq, opts ...client.Option) (*SendCaptchaRsp, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendCaptcha", varargs...)
	ret0, _ := ret[0].(*SendCaptchaRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendCaptcha indicates an expected call of SendCaptcha.
func (mr *MockCaptchaServerClientProxyMockRecorder) SendCaptcha(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendCaptcha", reflect.TypeOf((*MockCaptchaServerClientProxy)(nil).SendCaptcha), varargs...)
}
