// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: rcmd.proto

package rcmd

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RcmdProblemReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int32                  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"` // 用户编号
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`   // 返回的数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RcmdProblemReq) Reset() {
	*x = RcmdProblemReq{}
	mi := &file_rcmd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RcmdProblemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RcmdProblemReq) ProtoMessage() {}

func (x *RcmdProblemReq) ProtoReflect() protoreflect.Message {
	mi := &file_rcmd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RcmdProblemReq.ProtoReflect.Descriptor instead.
func (*RcmdProblemReq) Descriptor() ([]byte, []int) {
	return file_rcmd_proto_rawDescGZIP(), []int{0}
}

func (x *RcmdProblemReq) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *RcmdProblemReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RcmdProblemRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`   // 返回信息
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`        // 返回码
	Problems      []*ProblemInfo         `protobuf:"bytes,3,rep,name=problems,proto3" json:"problems,omitempty"` // 题目信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RcmdProblemRsp) Reset() {
	*x = RcmdProblemRsp{}
	mi := &file_rcmd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RcmdProblemRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RcmdProblemRsp) ProtoMessage() {}

func (x *RcmdProblemRsp) ProtoReflect() protoreflect.Message {
	mi := &file_rcmd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RcmdProblemRsp.ProtoReflect.Descriptor instead.
func (*RcmdProblemRsp) Descriptor() ([]byte, []int) {
	return file_rcmd_proto_rawDescGZIP(), []int{1}
}

func (x *RcmdProblemRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RcmdProblemRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RcmdProblemRsp) GetProblems() []*ProblemInfo {
	if x != nil {
		return x.Problems
	}
	return nil
}

type ProblemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProblemID     int32                  `protobuf:"varint,1,opt,name=problemID,proto3" json:"problemID,omitempty"`    // 题目编号
	ProblemName   string                 `protobuf:"bytes,2,opt,name=problemName,proto3" json:"problemName,omitempty"` // 题目名称
	RcmdReason    string                 `protobuf:"bytes,3,opt,name=rcmdReason,proto3" json:"rcmdReason,omitempty"`   // 推荐理由
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProblemInfo) Reset() {
	*x = ProblemInfo{}
	mi := &file_rcmd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProblemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProblemInfo) ProtoMessage() {}

func (x *ProblemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rcmd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProblemInfo.ProtoReflect.Descriptor instead.
func (*ProblemInfo) Descriptor() ([]byte, []int) {
	return file_rcmd_proto_rawDescGZIP(), []int{2}
}

func (x *ProblemInfo) GetProblemID() int32 {
	if x != nil {
		return x.ProblemID
	}
	return 0
}

func (x *ProblemInfo) GetProblemName() string {
	if x != nil {
		return x.ProblemName
	}
	return ""
}

func (x *ProblemInfo) GetRcmdReason() string {
	if x != nil {
		return x.RcmdReason
	}
	return ""
}

var File_rcmd_proto protoreflect.FileDescriptor

const file_rcmd_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"rcmd.proto\x12\aoj.rcmd\">\n" +
	"\x0eRcmdProblemReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x05R\x06userID\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"p\n" +
	"\x0eRcmdProblemRsp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x120\n" +
	"\bproblems\x18\x03 \x03(\v2\x14.oj.rcmd.ProblemInfoR\bproblems\"m\n" +
	"\vProblemInfo\x12\x1c\n" +
	"\tproblemID\x18\x01 \x01(\x05R\tproblemID\x12 \n" +
	"\vproblemName\x18\x02 \x01(\tR\vproblemName\x12\x1e\n" +
	"\n" +
	"rcmdReason\x18\x03 \x01(\tR\n" +
	"rcmdReason2O\n" +
	"\n" +
	"RcmdServer\x12A\n" +
	"\vRcmdProblem\x12\x17.oj.rcmd.RcmdProblemReq\x1a\x17.oj.rcmd.RcmdProblemRsp\"\x00B%Z#github.com/csuJudge/judgeProto/rcmdb\x06proto3"

var (
	file_rcmd_proto_rawDescOnce sync.Once
	file_rcmd_proto_rawDescData []byte
)

func file_rcmd_proto_rawDescGZIP() []byte {
	file_rcmd_proto_rawDescOnce.Do(func() {
		file_rcmd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rcmd_proto_rawDesc), len(file_rcmd_proto_rawDesc)))
	})
	return file_rcmd_proto_rawDescData
}

var file_rcmd_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rcmd_proto_goTypes = []any{
	(*RcmdProblemReq)(nil), // 0: oj.rcmd.RcmdProblemReq
	(*RcmdProblemRsp)(nil), // 1: oj.rcmd.RcmdProblemRsp
	(*ProblemInfo)(nil),    // 2: oj.rcmd.ProblemInfo
}
var file_rcmd_proto_depIdxs = []int32{
	2, // 0: oj.rcmd.RcmdProblemRsp.problems:type_name -> oj.rcmd.ProblemInfo
	0, // 1: oj.rcmd.RcmdServer.RcmdProblem:input_type -> oj.rcmd.RcmdProblemReq
	1, // 2: oj.rcmd.RcmdServer.RcmdProblem:output_type -> oj.rcmd.RcmdProblemRsp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rcmd_proto_init() }
func file_rcmd_proto_init() {
	if File_rcmd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rcmd_proto_rawDesc), len(file_rcmd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rcmd_proto_goTypes,
		DependencyIndexes: file_rcmd_proto_depIdxs,
		MessageInfos:      file_rcmd_proto_msgTypes,
	}.Build()
	File_rcmd_proto = out.File
	file_rcmd_proto_goTypes = nil
	file_rcmd_proto_depIdxs = nil
}
