// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: knowledge.proto

package judgeProto

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// KnowledgeServerService defines service.
type KnowledgeServerService interface {
	QueryKnowledge(ctx context.Context, req *QueryKnowledgeReq) (*QueryKnowledgeRsp, error)

	AddKnowledge(ctx context.Context, req *AddKnowledgeReq) (*AddKnowledgeRsp, error)

	QueryProblemKnowledge(ctx context.Context, req *QueryProblemKnowledgeReq) (*QueryProblemKnowledgeRsp, error)
}

func KnowledgeServerService_QueryKnowledge_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &QueryKnowledgeReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(KnowledgeServerService).QueryKnowledge(ctx, reqbody.(*QueryKnowledgeReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func KnowledgeServerService_AddKnowledge_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &AddKnowledgeReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(KnowledgeServerService).AddKnowledge(ctx, reqbody.(*AddKnowledgeReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func KnowledgeServerService_QueryProblemKnowledge_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &QueryProblemKnowledgeReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(KnowledgeServerService).QueryProblemKnowledge(ctx, reqbody.(*QueryProblemKnowledgeReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// KnowledgeServerServer_ServiceDesc descriptor for server.RegisterService.
var KnowledgeServerServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "oj.knowledge.KnowledgeServer",
	HandlerType: ((*KnowledgeServerService)(nil)),
	Methods: []server.Method{
		{
			Name: "/oj.knowledge.KnowledgeServer/QueryKnowledge",
			Func: KnowledgeServerService_QueryKnowledge_Handler,
		},
		{
			Name: "/oj.knowledge.KnowledgeServer/AddKnowledge",
			Func: KnowledgeServerService_AddKnowledge_Handler,
		},
		{
			Name: "/oj.knowledge.KnowledgeServer/QueryProblemKnowledge",
			Func: KnowledgeServerService_QueryProblemKnowledge_Handler,
		},
	},
}

// RegisterKnowledgeServerService registers service.
func RegisterKnowledgeServerService(s server.Service, svr KnowledgeServerService) {
	if err := s.Register(&KnowledgeServerServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("KnowledgeServer register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedKnowledgeServer struct{}

func (s *UnimplementedKnowledgeServer) QueryKnowledge(ctx context.Context, req *QueryKnowledgeReq) (*QueryKnowledgeRsp, error) {
	return nil, errors.New("rpc QueryKnowledge of service KnowledgeServer is not implemented")
}
func (s *UnimplementedKnowledgeServer) AddKnowledge(ctx context.Context, req *AddKnowledgeReq) (*AddKnowledgeRsp, error) {
	return nil, errors.New("rpc AddKnowledge of service KnowledgeServer is not implemented")
}
func (s *UnimplementedKnowledgeServer) QueryProblemKnowledge(ctx context.Context, req *QueryProblemKnowledgeReq) (*QueryProblemKnowledgeRsp, error) {
	return nil, errors.New("rpc QueryProblemKnowledge of service KnowledgeServer is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// KnowledgeServerClientProxy defines service client proxy
type KnowledgeServerClientProxy interface {
	QueryKnowledge(ctx context.Context, req *QueryKnowledgeReq, opts ...client.Option) (rsp *QueryKnowledgeRsp, err error)

	AddKnowledge(ctx context.Context, req *AddKnowledgeReq, opts ...client.Option) (rsp *AddKnowledgeRsp, err error)

	QueryProblemKnowledge(ctx context.Context, req *QueryProblemKnowledgeReq, opts ...client.Option) (rsp *QueryProblemKnowledgeRsp, err error)
}

type KnowledgeServerClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewKnowledgeServerClientProxy = func(opts ...client.Option) KnowledgeServerClientProxy {
	return &KnowledgeServerClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *KnowledgeServerClientProxyImpl) QueryKnowledge(ctx context.Context, req *QueryKnowledgeReq, opts ...client.Option) (*QueryKnowledgeRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.knowledge.KnowledgeServer/QueryKnowledge")
	msg.WithCalleeServiceName(KnowledgeServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("KnowledgeServer")
	msg.WithCalleeMethod("QueryKnowledge")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &QueryKnowledgeRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *KnowledgeServerClientProxyImpl) AddKnowledge(ctx context.Context, req *AddKnowledgeReq, opts ...client.Option) (*AddKnowledgeRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.knowledge.KnowledgeServer/AddKnowledge")
	msg.WithCalleeServiceName(KnowledgeServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("KnowledgeServer")
	msg.WithCalleeMethod("AddKnowledge")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &AddKnowledgeRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *KnowledgeServerClientProxyImpl) QueryProblemKnowledge(ctx context.Context, req *QueryProblemKnowledgeReq, opts ...client.Option) (*QueryProblemKnowledgeRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.knowledge.KnowledgeServer/QueryProblemKnowledge")
	msg.WithCalleeServiceName(KnowledgeServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("KnowledgeServer")
	msg.WithCalleeMethod("QueryProblemKnowledge")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &QueryProblemKnowledgeRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
