// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: ai.proto

package ai

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// AIServerService defines service.
type AIServerService interface {
	// IsCanUseAIAsk IsCanUseAIAsk 是否能询问AI
	IsCanUseAIAsk(ctx context.Context, req *IsCanUseAIAskReq) (*IsCanUseAIAskRsp, error)
	// Ask Ask 询问AI
	Ask(ctx context.Context, req *AskReq) (*AskRsp, error)
	// QueryAskHistory QueryAskHistory 查询询问历史
	QueryAskHistory(ctx context.Context, req *QueryAskHistoryReq) (*QueryAskHistoryRsp, error)
}

func AIServerService_IsCanUseAIAsk_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &IsCanUseAIAskReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AIServerService).IsCanUseAIAsk(ctx, reqbody.(*IsCanUseAIAskReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AIServerService_Ask_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &AskReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AIServerService).Ask(ctx, reqbody.(*AskReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AIServerService_QueryAskHistory_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &QueryAskHistoryReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AIServerService).QueryAskHistory(ctx, reqbody.(*QueryAskHistoryReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// AIServerServer_ServiceDesc descriptor for server.RegisterService.
var AIServerServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "oj.ai.AIServer",
	HandlerType: ((*AIServerService)(nil)),
	Methods: []server.Method{
		{
			Name: "/oj.ai.AIServer/IsCanUseAIAsk",
			Func: AIServerService_IsCanUseAIAsk_Handler,
		},
		{
			Name: "/oj.ai.AIServer/Ask",
			Func: AIServerService_Ask_Handler,
		},
		{
			Name: "/oj.ai.AIServer/QueryAskHistory",
			Func: AIServerService_QueryAskHistory_Handler,
		},
	},
}

// RegisterAIServerService registers service.
func RegisterAIServerService(s server.Service, svr AIServerService) {
	if err := s.Register(&AIServerServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("AIServer register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedAIServer struct{}

// IsCanUseAIAsk IsCanUseAIAsk 是否能询问AI
func (s *UnimplementedAIServer) IsCanUseAIAsk(ctx context.Context, req *IsCanUseAIAskReq) (*IsCanUseAIAskRsp, error) {
	return nil, errors.New("rpc IsCanUseAIAsk of service AIServer is not implemented")
}

// Ask Ask 询问AI
func (s *UnimplementedAIServer) Ask(ctx context.Context, req *AskReq) (*AskRsp, error) {
	return nil, errors.New("rpc Ask of service AIServer is not implemented")
}

// QueryAskHistory QueryAskHistory 查询询问历史
func (s *UnimplementedAIServer) QueryAskHistory(ctx context.Context, req *QueryAskHistoryReq) (*QueryAskHistoryRsp, error) {
	return nil, errors.New("rpc QueryAskHistory of service AIServer is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// AIServerClientProxy defines service client proxy
type AIServerClientProxy interface {
	// IsCanUseAIAsk IsCanUseAIAsk 是否能询问AI
	IsCanUseAIAsk(ctx context.Context, req *IsCanUseAIAskReq, opts ...client.Option) (rsp *IsCanUseAIAskRsp, err error)
	// Ask Ask 询问AI
	Ask(ctx context.Context, req *AskReq, opts ...client.Option) (rsp *AskRsp, err error)
	// QueryAskHistory QueryAskHistory 查询询问历史
	QueryAskHistory(ctx context.Context, req *QueryAskHistoryReq, opts ...client.Option) (rsp *QueryAskHistoryRsp, err error)
}

type AIServerClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewAIServerClientProxy = func(opts ...client.Option) AIServerClientProxy {
	return &AIServerClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *AIServerClientProxyImpl) IsCanUseAIAsk(ctx context.Context, req *IsCanUseAIAskReq, opts ...client.Option) (*IsCanUseAIAskRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.ai.AIServer/IsCanUseAIAsk")
	msg.WithCalleeServiceName(AIServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("AIServer")
	msg.WithCalleeMethod("IsCanUseAIAsk")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &IsCanUseAIAskRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AIServerClientProxyImpl) Ask(ctx context.Context, req *AskReq, opts ...client.Option) (*AskRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.ai.AIServer/Ask")
	msg.WithCalleeServiceName(AIServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("AIServer")
	msg.WithCalleeMethod("Ask")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &AskRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AIServerClientProxyImpl) QueryAskHistory(ctx context.Context, req *QueryAskHistoryReq, opts ...client.Option) (*QueryAskHistoryRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.ai.AIServer/QueryAskHistory")
	msg.WithCalleeServiceName(AIServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("AIServer")
	msg.WithCalleeMethod("QueryAskHistory")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &QueryAskHistoryRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
