// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: problem.proto

package problem

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// ProblemServerService defines service.
type ProblemServerService interface {
	// QueryProblem QueryProblem 查询题目
	QueryProblem(ctx context.Context, req *QueryProblemReq) (*QueryProblemRsp, error)
	// AddProblem AddProblem 添加题目
	AddProblem(ctx context.Context, req *AddProblemReq) (*CommonRsp, error)
	// QueryProblemDataList QueryProblemDataList 查询题目样例
	QueryProblemDataList(ctx context.Context, req *QueryProblemDataListReq) (*QueryProblemDataListRsp, error)
	// QueryProblemData QueryProblemData 查询题目样例数据
	QueryProblemData(ctx context.Context, req *QueryProblemDataReq) (*QueryProblemDataRsp, error)
	// AddProblemData AddProblemData 添加题目样例数据
	AddProblemData(ctx context.Context, req *AddProblemDataReq) (*CommonRsp, error)
	// UpdateProblemData UpdateProblemData 更新题目样例数据
	UpdateProblemData(ctx context.Context, req *UpdateProblemDataReq) (*CommonRsp, error)
	// DeleteProblemData DeleteProblemData 删除题目样例数据
	DeleteProblemData(ctx context.Context, req *DeleteProblemDataReq) (*CommonRsp, error)
}

func ProblemServerService_QueryProblem_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &QueryProblemReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ProblemServerService).QueryProblem(ctx, reqbody.(*QueryProblemReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func ProblemServerService_AddProblem_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &AddProblemReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ProblemServerService).AddProblem(ctx, reqbody.(*AddProblemReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func ProblemServerService_QueryProblemDataList_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &QueryProblemDataListReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ProblemServerService).QueryProblemDataList(ctx, reqbody.(*QueryProblemDataListReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func ProblemServerService_QueryProblemData_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &QueryProblemDataReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ProblemServerService).QueryProblemData(ctx, reqbody.(*QueryProblemDataReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func ProblemServerService_AddProblemData_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &AddProblemDataReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ProblemServerService).AddProblemData(ctx, reqbody.(*AddProblemDataReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func ProblemServerService_UpdateProblemData_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &UpdateProblemDataReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ProblemServerService).UpdateProblemData(ctx, reqbody.(*UpdateProblemDataReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func ProblemServerService_DeleteProblemData_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &DeleteProblemDataReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ProblemServerService).DeleteProblemData(ctx, reqbody.(*DeleteProblemDataReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// ProblemServerServer_ServiceDesc descriptor for server.RegisterService.
var ProblemServerServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "oj.problem.ProblemServer",
	HandlerType: ((*ProblemServerService)(nil)),
	Methods: []server.Method{
		{
			Name: "/oj.problem.ProblemServer/QueryProblem",
			Func: ProblemServerService_QueryProblem_Handler,
		},
		{
			Name: "/oj.problem.ProblemServer/AddProblem",
			Func: ProblemServerService_AddProblem_Handler,
		},
		{
			Name: "/oj.problem.ProblemServer/QueryProblemDataList",
			Func: ProblemServerService_QueryProblemDataList_Handler,
		},
		{
			Name: "/oj.problem.ProblemServer/QueryProblemData",
			Func: ProblemServerService_QueryProblemData_Handler,
		},
		{
			Name: "/oj.problem.ProblemServer/AddProblemData",
			Func: ProblemServerService_AddProblemData_Handler,
		},
		{
			Name: "/oj.problem.ProblemServer/UpdateProblemData",
			Func: ProblemServerService_UpdateProblemData_Handler,
		},
		{
			Name: "/oj.problem.ProblemServer/DeleteProblemData",
			Func: ProblemServerService_DeleteProblemData_Handler,
		},
	},
}

// RegisterProblemServerService registers service.
func RegisterProblemServerService(s server.Service, svr ProblemServerService) {
	if err := s.Register(&ProblemServerServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("ProblemServer register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedProblemServer struct{}

// QueryProblem QueryProblem 查询题目
func (s *UnimplementedProblemServer) QueryProblem(ctx context.Context, req *QueryProblemReq) (*QueryProblemRsp, error) {
	return nil, errors.New("rpc QueryProblem of service ProblemServer is not implemented")
}

// AddProblem AddProblem 添加题目
func (s *UnimplementedProblemServer) AddProblem(ctx context.Context, req *AddProblemReq) (*CommonRsp, error) {
	return nil, errors.New("rpc AddProblem of service ProblemServer is not implemented")
}

// QueryProblemDataList QueryProblemDataList 查询题目样例
func (s *UnimplementedProblemServer) QueryProblemDataList(ctx context.Context, req *QueryProblemDataListReq) (*QueryProblemDataListRsp, error) {
	return nil, errors.New("rpc QueryProblemDataList of service ProblemServer is not implemented")
}

// QueryProblemData QueryProblemData 查询题目样例数据
func (s *UnimplementedProblemServer) QueryProblemData(ctx context.Context, req *QueryProblemDataReq) (*QueryProblemDataRsp, error) {
	return nil, errors.New("rpc QueryProblemData of service ProblemServer is not implemented")
}

// AddProblemData AddProblemData 添加题目样例数据
func (s *UnimplementedProblemServer) AddProblemData(ctx context.Context, req *AddProblemDataReq) (*CommonRsp, error) {
	return nil, errors.New("rpc AddProblemData of service ProblemServer is not implemented")
}

// UpdateProblemData UpdateProblemData 更新题目样例数据
func (s *UnimplementedProblemServer) UpdateProblemData(ctx context.Context, req *UpdateProblemDataReq) (*CommonRsp, error) {
	return nil, errors.New("rpc UpdateProblemData of service ProblemServer is not implemented")
}

// DeleteProblemData DeleteProblemData 删除题目样例数据
func (s *UnimplementedProblemServer) DeleteProblemData(ctx context.Context, req *DeleteProblemDataReq) (*CommonRsp, error) {
	return nil, errors.New("rpc DeleteProblemData of service ProblemServer is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// ProblemServerClientProxy defines service client proxy
type ProblemServerClientProxy interface {
	// QueryProblem QueryProblem 查询题目
	QueryProblem(ctx context.Context, req *QueryProblemReq, opts ...client.Option) (rsp *QueryProblemRsp, err error)
	// AddProblem AddProblem 添加题目
	AddProblem(ctx context.Context, req *AddProblemReq, opts ...client.Option) (rsp *CommonRsp, err error)
	// QueryProblemDataList QueryProblemDataList 查询题目样例
	QueryProblemDataList(ctx context.Context, req *QueryProblemDataListReq, opts ...client.Option) (rsp *QueryProblemDataListRsp, err error)
	// QueryProblemData QueryProblemData 查询题目样例数据
	QueryProblemData(ctx context.Context, req *QueryProblemDataReq, opts ...client.Option) (rsp *QueryProblemDataRsp, err error)
	// AddProblemData AddProblemData 添加题目样例数据
	AddProblemData(ctx context.Context, req *AddProblemDataReq, opts ...client.Option) (rsp *CommonRsp, err error)
	// UpdateProblemData UpdateProblemData 更新题目样例数据
	UpdateProblemData(ctx context.Context, req *UpdateProblemDataReq, opts ...client.Option) (rsp *CommonRsp, err error)
	// DeleteProblemData DeleteProblemData 删除题目样例数据
	DeleteProblemData(ctx context.Context, req *DeleteProblemDataReq, opts ...client.Option) (rsp *CommonRsp, err error)
}

type ProblemServerClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewProblemServerClientProxy = func(opts ...client.Option) ProblemServerClientProxy {
	return &ProblemServerClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *ProblemServerClientProxyImpl) QueryProblem(ctx context.Context, req *QueryProblemReq, opts ...client.Option) (*QueryProblemRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.problem.ProblemServer/QueryProblem")
	msg.WithCalleeServiceName(ProblemServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("ProblemServer")
	msg.WithCalleeMethod("QueryProblem")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &QueryProblemRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *ProblemServerClientProxyImpl) AddProblem(ctx context.Context, req *AddProblemReq, opts ...client.Option) (*CommonRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.problem.ProblemServer/AddProblem")
	msg.WithCalleeServiceName(ProblemServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("ProblemServer")
	msg.WithCalleeMethod("AddProblem")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CommonRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *ProblemServerClientProxyImpl) QueryProblemDataList(ctx context.Context, req *QueryProblemDataListReq, opts ...client.Option) (*QueryProblemDataListRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.problem.ProblemServer/QueryProblemDataList")
	msg.WithCalleeServiceName(ProblemServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("ProblemServer")
	msg.WithCalleeMethod("QueryProblemDataList")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &QueryProblemDataListRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *ProblemServerClientProxyImpl) QueryProblemData(ctx context.Context, req *QueryProblemDataReq, opts ...client.Option) (*QueryProblemDataRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.problem.ProblemServer/QueryProblemData")
	msg.WithCalleeServiceName(ProblemServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("ProblemServer")
	msg.WithCalleeMethod("QueryProblemData")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &QueryProblemDataRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *ProblemServerClientProxyImpl) AddProblemData(ctx context.Context, req *AddProblemDataReq, opts ...client.Option) (*CommonRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.problem.ProblemServer/AddProblemData")
	msg.WithCalleeServiceName(ProblemServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("ProblemServer")
	msg.WithCalleeMethod("AddProblemData")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CommonRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *ProblemServerClientProxyImpl) UpdateProblemData(ctx context.Context, req *UpdateProblemDataReq, opts ...client.Option) (*CommonRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.problem.ProblemServer/UpdateProblemData")
	msg.WithCalleeServiceName(ProblemServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("ProblemServer")
	msg.WithCalleeMethod("UpdateProblemData")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CommonRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *ProblemServerClientProxyImpl) DeleteProblemData(ctx context.Context, req *DeleteProblemDataReq, opts ...client.Option) (*CommonRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.problem.ProblemServer/DeleteProblemData")
	msg.WithCalleeServiceName(ProblemServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("ProblemServer")
	msg.WithCalleeMethod("DeleteProblemData")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CommonRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
