// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: school.proto

package school

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// CourseServerService defines service.
type CourseServerService interface {
	// AddCourse AddCourse 添加课程
	AddCourse(ctx context.Context, req *AddCourseReq) (*CommonRsp, error)
	// UpdateCourse UpdateCourse 更新课程
	UpdateCourse(ctx context.Context, req *UpdateCourseReq) (*CommonRsp, error)
	// UpdateCourseStatus UpdateCourse 更新课程状态
	UpdateCourseStatus(ctx context.Context, req *UpdateCourseStatusReq) (*CommonRsp, error)
}

func CourseServerService_AddCourse_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &AddCourseReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CourseServerService).AddCourse(ctx, reqbody.(*AddCourseReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CourseServerService_UpdateCourse_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &UpdateCourseReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CourseServerService).UpdateCourse(ctx, reqbody.(*UpdateCourseReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func CourseServerService_UpdateCourseStatus_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &UpdateCourseStatusReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(CourseServerService).UpdateCourseStatus(ctx, reqbody.(*UpdateCourseStatusReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// CourseServerServer_ServiceDesc descriptor for server.RegisterService.
var CourseServerServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "oj.school.CourseServer",
	HandlerType: ((*CourseServerService)(nil)),
	Methods: []server.Method{
		{
			Name: "/oj.school.CourseServer/AddCourse",
			Func: CourseServerService_AddCourse_Handler,
		},
		{
			Name: "/oj.school.CourseServer/UpdateCourse",
			Func: CourseServerService_UpdateCourse_Handler,
		},
		{
			Name: "/oj.school.CourseServer/UpdateCourseStatus",
			Func: CourseServerService_UpdateCourseStatus_Handler,
		},
	},
}

// RegisterCourseServerService registers service.
func RegisterCourseServerService(s server.Service, svr CourseServerService) {
	if err := s.Register(&CourseServerServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("CourseServer register error:%v", err))
	}
}

// ClassServerService defines service.
type ClassServerService interface {
	// QueryUserClass QueryUserClass 查询用户的班级
	QueryUserClass(ctx context.Context, req *QueryUserClassReq) (*QueryUserClassRsp, error)
	// AddClass AddClass 添加班级
	AddClass(ctx context.Context, req *AddClassReq) (*CommonRsp, error)
	// UpdateClass UpdateClass 更新班级
	UpdateClass(ctx context.Context, req *UpdateClassReq) (*CommonRsp, error)
	// UpdateClassStatus UpdateClassStatus 更新班级状态
	UpdateClassStatus(ctx context.Context, req *UpdateClassStatusReq) (*CommonRsp, error)
	// UpdateClassUser UpdateClassUser 更新班级的人
	UpdateClassUser(ctx context.Context, req *UpdateClassUserReq) (*CommonRsp, error)
	// QueryClassUser QueryClassUser 查询班级用户
	QueryClassUser(ctx context.Context, req *QueryClassUserReq) (*QueryClassUserRsp, error)
	// QueryClassPageSize QueryClassPageSize 分页查询班级
	QueryClassPageSize(ctx context.Context, req *QueryClassPageSizeReq) (*QueryClassPageSizeRsp, error)
	// QueryClass QueryClass 查询班级
	QueryClass(ctx context.Context, req *QueryClassReq) (*QueryClassRsp, error)
}

func ClassServerService_QueryUserClass_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &QueryUserClassReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ClassServerService).QueryUserClass(ctx, reqbody.(*QueryUserClassReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func ClassServerService_AddClass_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &AddClassReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ClassServerService).AddClass(ctx, reqbody.(*AddClassReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func ClassServerService_UpdateClass_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &UpdateClassReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ClassServerService).UpdateClass(ctx, reqbody.(*UpdateClassReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func ClassServerService_UpdateClassStatus_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &UpdateClassStatusReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ClassServerService).UpdateClassStatus(ctx, reqbody.(*UpdateClassStatusReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func ClassServerService_UpdateClassUser_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &UpdateClassUserReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ClassServerService).UpdateClassUser(ctx, reqbody.(*UpdateClassUserReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func ClassServerService_QueryClassUser_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &QueryClassUserReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ClassServerService).QueryClassUser(ctx, reqbody.(*QueryClassUserReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func ClassServerService_QueryClassPageSize_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &QueryClassPageSizeReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ClassServerService).QueryClassPageSize(ctx, reqbody.(*QueryClassPageSizeReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func ClassServerService_QueryClass_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &QueryClassReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ClassServerService).QueryClass(ctx, reqbody.(*QueryClassReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// ClassServerServer_ServiceDesc descriptor for server.RegisterService.
var ClassServerServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "oj.school.ClassServer",
	HandlerType: ((*ClassServerService)(nil)),
	Methods: []server.Method{
		{
			Name: "/oj.school.ClassServer/QueryUserClass",
			Func: ClassServerService_QueryUserClass_Handler,
		},
		{
			Name: "/oj.school.ClassServer/AddClass",
			Func: ClassServerService_AddClass_Handler,
		},
		{
			Name: "/oj.school.ClassServer/UpdateClass",
			Func: ClassServerService_UpdateClass_Handler,
		},
		{
			Name: "/oj.school.ClassServer/UpdateClassStatus",
			Func: ClassServerService_UpdateClassStatus_Handler,
		},
		{
			Name: "/oj.school.ClassServer/UpdateClassUser",
			Func: ClassServerService_UpdateClassUser_Handler,
		},
		{
			Name: "/oj.school.ClassServer/QueryClassUser",
			Func: ClassServerService_QueryClassUser_Handler,
		},
		{
			Name: "/oj.school.ClassServer/QueryClassPageSize",
			Func: ClassServerService_QueryClassPageSize_Handler,
		},
		{
			Name: "/oj.school.ClassServer/QueryClass",
			Func: ClassServerService_QueryClass_Handler,
		},
	},
}

// RegisterClassServerService registers service.
func RegisterClassServerService(s server.Service, svr ClassServerService) {
	if err := s.Register(&ClassServerServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("ClassServer register error:%v", err))
	}
}

// TermServerService defines service.
type TermServerService interface {
	// AddTerm AddTerm 添加学期
	AddTerm(ctx context.Context, req *AddTermReq) (*CommonRsp, error)
	// UpdateTerm UpdateTerm 更新课程
	UpdateTerm(ctx context.Context, req *UpdateTermReq) (*CommonRsp, error)
	// UpdateTermStatus UpdateTerm 更新课程状态
	UpdateTermStatus(ctx context.Context, req *UpdateTermStatusReq) (*CommonRsp, error)
}

func TermServerService_AddTerm_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &AddTermReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(TermServerService).AddTerm(ctx, reqbody.(*AddTermReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func TermServerService_UpdateTerm_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &UpdateTermReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(TermServerService).UpdateTerm(ctx, reqbody.(*UpdateTermReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func TermServerService_UpdateTermStatus_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &UpdateTermStatusReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(TermServerService).UpdateTermStatus(ctx, reqbody.(*UpdateTermStatusReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// TermServerServer_ServiceDesc descriptor for server.RegisterService.
var TermServerServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "oj.school.TermServer",
	HandlerType: ((*TermServerService)(nil)),
	Methods: []server.Method{
		{
			Name: "/oj.school.TermServer/AddTerm",
			Func: TermServerService_AddTerm_Handler,
		},
		{
			Name: "/oj.school.TermServer/UpdateTerm",
			Func: TermServerService_UpdateTerm_Handler,
		},
		{
			Name: "/oj.school.TermServer/UpdateTermStatus",
			Func: TermServerService_UpdateTermStatus_Handler,
		},
	},
}

// RegisterTermServerService registers service.
func RegisterTermServerService(s server.Service, svr TermServerService) {
	if err := s.Register(&TermServerServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("TermServer register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedCourseServer struct{}

// AddCourse AddCourse 添加课程
func (s *UnimplementedCourseServer) AddCourse(ctx context.Context, req *AddCourseReq) (*CommonRsp, error) {
	return nil, errors.New("rpc AddCourse of service CourseServer is not implemented")
}

// UpdateCourse UpdateCourse 更新课程
func (s *UnimplementedCourseServer) UpdateCourse(ctx context.Context, req *UpdateCourseReq) (*CommonRsp, error) {
	return nil, errors.New("rpc UpdateCourse of service CourseServer is not implemented")
}

// UpdateCourseStatus UpdateCourse 更新课程状态
func (s *UnimplementedCourseServer) UpdateCourseStatus(ctx context.Context, req *UpdateCourseStatusReq) (*CommonRsp, error) {
	return nil, errors.New("rpc UpdateCourseStatus of service CourseServer is not implemented")
}

type UnimplementedClassServer struct{}

// QueryUserClass QueryUserClass 查询用户的班级
func (s *UnimplementedClassServer) QueryUserClass(ctx context.Context, req *QueryUserClassReq) (*QueryUserClassRsp, error) {
	return nil, errors.New("rpc QueryUserClass of service ClassServer is not implemented")
}

// AddClass AddClass 添加班级
func (s *UnimplementedClassServer) AddClass(ctx context.Context, req *AddClassReq) (*CommonRsp, error) {
	return nil, errors.New("rpc AddClass of service ClassServer is not implemented")
}

// UpdateClass UpdateClass 更新班级
func (s *UnimplementedClassServer) UpdateClass(ctx context.Context, req *UpdateClassReq) (*CommonRsp, error) {
	return nil, errors.New("rpc UpdateClass of service ClassServer is not implemented")
}

// UpdateClassStatus UpdateClassStatus 更新班级状态
func (s *UnimplementedClassServer) UpdateClassStatus(ctx context.Context, req *UpdateClassStatusReq) (*CommonRsp, error) {
	return nil, errors.New("rpc UpdateClassStatus of service ClassServer is not implemented")
}

// UpdateClassUser UpdateClassUser 更新班级的人
func (s *UnimplementedClassServer) UpdateClassUser(ctx context.Context, req *UpdateClassUserReq) (*CommonRsp, error) {
	return nil, errors.New("rpc UpdateClassUser of service ClassServer is not implemented")
}

// QueryClassUser QueryClassUser 查询班级用户
func (s *UnimplementedClassServer) QueryClassUser(ctx context.Context, req *QueryClassUserReq) (*QueryClassUserRsp, error) {
	return nil, errors.New("rpc QueryClassUser of service ClassServer is not implemented")
}

// QueryClassPageSize QueryClassPageSize 分页查询班级
func (s *UnimplementedClassServer) QueryClassPageSize(ctx context.Context, req *QueryClassPageSizeReq) (*QueryClassPageSizeRsp, error) {
	return nil, errors.New("rpc QueryClassPageSize of service ClassServer is not implemented")
}

// QueryClass QueryClass 查询班级
func (s *UnimplementedClassServer) QueryClass(ctx context.Context, req *QueryClassReq) (*QueryClassRsp, error) {
	return nil, errors.New("rpc QueryClass of service ClassServer is not implemented")
}

type UnimplementedTermServer struct{}

// AddTerm AddTerm 添加学期
func (s *UnimplementedTermServer) AddTerm(ctx context.Context, req *AddTermReq) (*CommonRsp, error) {
	return nil, errors.New("rpc AddTerm of service TermServer is not implemented")
}

// UpdateTerm UpdateTerm 更新课程
func (s *UnimplementedTermServer) UpdateTerm(ctx context.Context, req *UpdateTermReq) (*CommonRsp, error) {
	return nil, errors.New("rpc UpdateTerm of service TermServer is not implemented")
}

// UpdateTermStatus UpdateTerm 更新课程状态
func (s *UnimplementedTermServer) UpdateTermStatus(ctx context.Context, req *UpdateTermStatusReq) (*CommonRsp, error) {
	return nil, errors.New("rpc UpdateTermStatus of service TermServer is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// CourseServerClientProxy defines service client proxy
type CourseServerClientProxy interface {
	// AddCourse AddCourse 添加课程
	AddCourse(ctx context.Context, req *AddCourseReq, opts ...client.Option) (rsp *CommonRsp, err error)
	// UpdateCourse UpdateCourse 更新课程
	UpdateCourse(ctx context.Context, req *UpdateCourseReq, opts ...client.Option) (rsp *CommonRsp, err error)
	// UpdateCourseStatus UpdateCourse 更新课程状态
	UpdateCourseStatus(ctx context.Context, req *UpdateCourseStatusReq, opts ...client.Option) (rsp *CommonRsp, err error)
}

type CourseServerClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewCourseServerClientProxy = func(opts ...client.Option) CourseServerClientProxy {
	return &CourseServerClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *CourseServerClientProxyImpl) AddCourse(ctx context.Context, req *AddCourseReq, opts ...client.Option) (*CommonRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.school.CourseServer/AddCourse")
	msg.WithCalleeServiceName(CourseServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("CourseServer")
	msg.WithCalleeMethod("AddCourse")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CommonRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CourseServerClientProxyImpl) UpdateCourse(ctx context.Context, req *UpdateCourseReq, opts ...client.Option) (*CommonRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.school.CourseServer/UpdateCourse")
	msg.WithCalleeServiceName(CourseServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("CourseServer")
	msg.WithCalleeMethod("UpdateCourse")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CommonRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *CourseServerClientProxyImpl) UpdateCourseStatus(ctx context.Context, req *UpdateCourseStatusReq, opts ...client.Option) (*CommonRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.school.CourseServer/UpdateCourseStatus")
	msg.WithCalleeServiceName(CourseServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("CourseServer")
	msg.WithCalleeMethod("UpdateCourseStatus")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CommonRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// ClassServerClientProxy defines service client proxy
type ClassServerClientProxy interface {
	// QueryUserClass QueryUserClass 查询用户的班级
	QueryUserClass(ctx context.Context, req *QueryUserClassReq, opts ...client.Option) (rsp *QueryUserClassRsp, err error)
	// AddClass AddClass 添加班级
	AddClass(ctx context.Context, req *AddClassReq, opts ...client.Option) (rsp *CommonRsp, err error)
	// UpdateClass UpdateClass 更新班级
	UpdateClass(ctx context.Context, req *UpdateClassReq, opts ...client.Option) (rsp *CommonRsp, err error)
	// UpdateClassStatus UpdateClassStatus 更新班级状态
	UpdateClassStatus(ctx context.Context, req *UpdateClassStatusReq, opts ...client.Option) (rsp *CommonRsp, err error)
	// UpdateClassUser UpdateClassUser 更新班级的人
	UpdateClassUser(ctx context.Context, req *UpdateClassUserReq, opts ...client.Option) (rsp *CommonRsp, err error)
	// QueryClassUser QueryClassUser 查询班级用户
	QueryClassUser(ctx context.Context, req *QueryClassUserReq, opts ...client.Option) (rsp *QueryClassUserRsp, err error)
	// QueryClassPageSize QueryClassPageSize 分页查询班级
	QueryClassPageSize(ctx context.Context, req *QueryClassPageSizeReq, opts ...client.Option) (rsp *QueryClassPageSizeRsp, err error)
	// QueryClass QueryClass 查询班级
	QueryClass(ctx context.Context, req *QueryClassReq, opts ...client.Option) (rsp *QueryClassRsp, err error)
}

type ClassServerClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewClassServerClientProxy = func(opts ...client.Option) ClassServerClientProxy {
	return &ClassServerClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *ClassServerClientProxyImpl) QueryUserClass(ctx context.Context, req *QueryUserClassReq, opts ...client.Option) (*QueryUserClassRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.school.ClassServer/QueryUserClass")
	msg.WithCalleeServiceName(ClassServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("ClassServer")
	msg.WithCalleeMethod("QueryUserClass")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &QueryUserClassRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *ClassServerClientProxyImpl) AddClass(ctx context.Context, req *AddClassReq, opts ...client.Option) (*CommonRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.school.ClassServer/AddClass")
	msg.WithCalleeServiceName(ClassServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("ClassServer")
	msg.WithCalleeMethod("AddClass")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CommonRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *ClassServerClientProxyImpl) UpdateClass(ctx context.Context, req *UpdateClassReq, opts ...client.Option) (*CommonRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.school.ClassServer/UpdateClass")
	msg.WithCalleeServiceName(ClassServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("ClassServer")
	msg.WithCalleeMethod("UpdateClass")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CommonRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *ClassServerClientProxyImpl) UpdateClassStatus(ctx context.Context, req *UpdateClassStatusReq, opts ...client.Option) (*CommonRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.school.ClassServer/UpdateClassStatus")
	msg.WithCalleeServiceName(ClassServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("ClassServer")
	msg.WithCalleeMethod("UpdateClassStatus")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CommonRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *ClassServerClientProxyImpl) UpdateClassUser(ctx context.Context, req *UpdateClassUserReq, opts ...client.Option) (*CommonRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.school.ClassServer/UpdateClassUser")
	msg.WithCalleeServiceName(ClassServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("ClassServer")
	msg.WithCalleeMethod("UpdateClassUser")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CommonRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *ClassServerClientProxyImpl) QueryClassUser(ctx context.Context, req *QueryClassUserReq, opts ...client.Option) (*QueryClassUserRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.school.ClassServer/QueryClassUser")
	msg.WithCalleeServiceName(ClassServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("ClassServer")
	msg.WithCalleeMethod("QueryClassUser")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &QueryClassUserRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *ClassServerClientProxyImpl) QueryClassPageSize(ctx context.Context, req *QueryClassPageSizeReq, opts ...client.Option) (*QueryClassPageSizeRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.school.ClassServer/QueryClassPageSize")
	msg.WithCalleeServiceName(ClassServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("ClassServer")
	msg.WithCalleeMethod("QueryClassPageSize")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &QueryClassPageSizeRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *ClassServerClientProxyImpl) QueryClass(ctx context.Context, req *QueryClassReq, opts ...client.Option) (*QueryClassRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.school.ClassServer/QueryClass")
	msg.WithCalleeServiceName(ClassServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("ClassServer")
	msg.WithCalleeMethod("QueryClass")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &QueryClassRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// TermServerClientProxy defines service client proxy
type TermServerClientProxy interface {
	// AddTerm AddTerm 添加学期
	AddTerm(ctx context.Context, req *AddTermReq, opts ...client.Option) (rsp *CommonRsp, err error)
	// UpdateTerm UpdateTerm 更新课程
	UpdateTerm(ctx context.Context, req *UpdateTermReq, opts ...client.Option) (rsp *CommonRsp, err error)
	// UpdateTermStatus UpdateTerm 更新课程状态
	UpdateTermStatus(ctx context.Context, req *UpdateTermStatusReq, opts ...client.Option) (rsp *CommonRsp, err error)
}

type TermServerClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewTermServerClientProxy = func(opts ...client.Option) TermServerClientProxy {
	return &TermServerClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *TermServerClientProxyImpl) AddTerm(ctx context.Context, req *AddTermReq, opts ...client.Option) (*CommonRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.school.TermServer/AddTerm")
	msg.WithCalleeServiceName(TermServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("TermServer")
	msg.WithCalleeMethod("AddTerm")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CommonRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *TermServerClientProxyImpl) UpdateTerm(ctx context.Context, req *UpdateTermReq, opts ...client.Option) (*CommonRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.school.TermServer/UpdateTerm")
	msg.WithCalleeServiceName(TermServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("TermServer")
	msg.WithCalleeMethod("UpdateTerm")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CommonRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *TermServerClientProxyImpl) UpdateTermStatus(ctx context.Context, req *UpdateTermStatusReq, opts ...client.Option) (*CommonRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.school.TermServer/UpdateTermStatus")
	msg.WithCalleeServiceName(TermServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("TermServer")
	msg.WithCalleeMethod("UpdateTermStatus")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CommonRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
